version: "3.9"

services:
  app:
    container_name: monolito-app
    build:
      context: ./docker/php
    volumes:
      - ./app:/var/www/html
    environment:
      APP_ENV: local
      PHP_MEMORY_LIMIT: 512M
    depends_on:
      - mysql
      - redis

  web:
    container_name: monolito-web
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  mysql:
    container_name: monolito-mysql
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: monolito
      MYSQL_USER: monouser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    container_name: monolito-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"

  vite:
    container_name: monolito-vite
    image: node:20-alpine
    working_dir: /var/www/html
    command: sh -c "npm ci && npm run dev -- --host"
    ports:
      - "5173:5173"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - app

  queue:
    container_name: monolito-queue
    build:
      context: ./docker/php
    command: ["supervisord","-c","/etc/supervisor/conf.d/supervisord.conf"]
    volumes:
      - ./app:/var/www/html
      - ./docker/supervisor:/etc/supervisor/conf.d
    depends_on:
      - app
      - redis
  phpmyadmin:
    image: phpmyadmin:5.2
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: monouser
      PMA_PASSWORD: secret
    depends_on:
      - mysql

volumes:
  mysql_data: